"""Create the initial persistence schema.

Revision ID: 0001_initial
Revises: 
Create Date: 2026-07-28 06:49:01.506446
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('language_code', sa.String(length=16), server_default='en', nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'ONBOARDING_IN_PROGRESS', 'PROFILE_COMPLETED', 'BASELINE_PENDING', 'BASELINE_IMPORTING', 'BASELINE_READY', 'BASELINE_FAILED', name='user_status', native_enum=False, create_constraint=True, length=32), server_default='NEW', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('telegram_user_id', name='uq_users_telegram_user_id')
    )
    op.create_index('ix_users_telegram_user_id', 'users', ['telegram_user_id'], unique=False)
    op.create_table('activities',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('STRAVA', name='activity_source', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('sport', sa.Enum('RUN', 'RIDE', 'SWIM', 'STRENGTH', 'WALK_HIKE', 'OTHER', name='discipline', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('source_sport_type', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=128), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('moving_time_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('elevation_gain_meters', sa.Float(), nullable=True),
    sa.Column('average_heart_rate', sa.Float(), nullable=True),
    sa.Column('max_heart_rate', sa.Float(), nullable=True),
    sa.Column('average_speed', sa.Float(), nullable=True),
    sa.Column('average_watts', sa.Float(), nullable=True),
    sa.Column('trainer', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('commute', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('manual', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('raw_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('distance_meters IS NULL OR distance_meters >= 0', name=op.f('ck_activities_distance_nonnegative')),
    sa.CheckConstraint('duration_seconds >= 0', name=op.f('ck_activities_duration_nonnegative')),
    sa.CheckConstraint('elevation_gain_meters IS NULL OR elevation_gain_meters >= 0', name=op.f('ck_activities_elevation_nonnegative')),
    sa.CheckConstraint('moving_time_seconds IS NULL OR moving_time_seconds >= 0', name=op.f('ck_activities_moving_time_nonnegative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities')),
    sa.UniqueConstraint('source', 'external_id', name='uq_activities_source_external_id')
    )
    op.create_index('ix_activities_user_started_at', 'activities', ['user_id', 'started_at'], unique=False)
    op.create_table('athlete_baselines',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('analysis_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('analysis_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('STRAVA', 'MANUAL', 'CALIBRATION', 'SKIP_FOR_NOW', name='athlete_baseline_source', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('status', sa.Enum('READY', 'INSUFFICIENT_DATA', 'FAILED', name='baseline_status', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('analysis_end >= analysis_start', name=op.f('ck_athlete_baselines_analysis_period_order')),
    sa.CheckConstraint('overall_confidence >= 0 AND overall_confidence <= 1', name=op.f('ck_athlete_baselines_overall_confidence_range')),
    sa.CheckConstraint('version > 0', name=op.f('ck_athlete_baselines_positive_version')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_athlete_baselines_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_athlete_baselines')),
    sa.UniqueConstraint('user_id', 'version', name='uq_athlete_baselines_user_version')
    )
    op.create_index('ix_athlete_baselines_user_generated', 'athlete_baselines', ['user_id', 'generated_at'], unique=False)
    op.create_table('athlete_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('age', sa.SmallInteger(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('primary_sport', sa.Enum('RUNNING', 'CYCLING', 'TRIATHLON', 'SWIMMING', 'GENERAL_FITNESS', 'OTHER', name='primary_sport', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('age >= 16 AND age <= 100', name=op.f('ck_athlete_profiles_age_range')),
    sa.CheckConstraint('height_cm IS NULL OR (height_cm >= 120 AND height_cm <= 230)', name=op.f('ck_athlete_profiles_height_cm_range')),
    sa.CheckConstraint('weight_kg IS NULL OR (weight_kg >= 35 AND weight_kg <= 250)', name=op.f('ck_athlete_profiles_weight_kg_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_athlete_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_athlete_profiles')),
    sa.UniqueConstraint('user_id', name='uq_athlete_profiles_user_id')
    )
    op.create_table('availability_rules',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='day_of_week', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('available_minutes', sa.SmallInteger(), nullable=True),
    sa.Column('is_variable', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('available_minutes IS NULL OR available_minutes > 0', name=op.f('ck_availability_rules_positive_available_minutes')),
    sa.CheckConstraint('is_variable OR available_minutes IS NOT NULL', name=op.f('ck_availability_rules_variable_or_minutes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_availability_rules_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability_rules')),
    sa.UniqueConstraint('user_id', 'day_of_week', name='uq_availability_rules_user_day')
    )
    op.create_table('baseline_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('selected_source', sa.Enum('STRAVA', 'MANUAL', 'CALIBRATION', 'SKIP_FOR_NOW', name='baseline_source', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('status', sa.Enum('SELECTED', 'PENDING', 'IMPORTING', 'READY', 'NOT_IMPLEMENTED', 'FAILED', name='baseline_preference_status', native_enum=False, create_constraint=True, length=24), server_default='SELECTED', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_baseline_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_baseline_preferences')),
    sa.UniqueConstraint('user_id', name='uq_baseline_preferences_user_id')
    )
    op.create_table('coach_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tone', sa.Enum('DIRECT_DEMANDING', 'ANALYTICAL_DETAILED', 'CONCISE_PRACTICAL', 'SUPPORTIVE_MOTIVATIONAL', name='coach_tone', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('detail_level', sa.Enum('SHORT', 'MEDIUM', 'DETAILED', name='detail_level', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_coach_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coach_preferences')),
    sa.UniqueConstraint('user_id', name='uq_coach_preferences_user_id')
    )
    op.create_table('equipment_access',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('equipment_type', sa.Enum('RUNNING_SHOES', 'ROAD_BIKE', 'MOUNTAIN_BIKE', 'INDOOR_BIKE_TRAINER', 'SWIMMING_POOL', 'GYM', 'RESISTANCE_BANDS', 'SPORTS_WATCH', 'HEART_RATE_CHEST_STRAP', 'OTHER', name='equipment_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('access_type', sa.Enum('REGULAR', 'IRREGULAR', 'NO_REGULAR_ACCESS', name='equipment_access_type', native_enum=False, create_constraint=True, length=24), server_default='REGULAR', nullable=False),
    sa.Column('access_days', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_equipment_access_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_access')),
    sa.UniqueConstraint('user_id', 'equipment_type', name='uq_equipment_access_user_equipment')
    )
    op.create_table('health_constraints',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('body_area', sa.Enum('SHOULDER', 'BACK', 'HIP', 'KNEE', 'ANKLE_FOOT', 'OTHER', name='body_area', native_enum=False, create_constraint=True, length=24), nullable=True),
    sa.Column('constraint_type', sa.Enum('CURRENT', 'HISTORICAL', 'BOTH', name='health_constraint_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('normalized_description', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('is_historical', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(constraint_type = 'CURRENT' AND is_current AND NOT is_historical) OR (constraint_type = 'HISTORICAL' AND is_historical AND NOT is_current) OR (constraint_type = 'BOTH' AND is_current AND is_historical)", name=op.f('ck_health_constraints_timing_matches_flags')),
    sa.CheckConstraint('is_current OR is_historical', name=op.f('ck_health_constraints_current_or_historical')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_health_constraints_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_constraints'))
    )
    op.create_index('ix_health_constraints_user_id', 'health_constraints', ['user_id'], unique=False)
    op.create_table('llm_usage',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('onboarding_step', sa.Enum('CONSENT', 'PRIMARY_SPORT', 'GOAL_TYPE', 'EVENT_STATUS', 'EVENT_NAME', 'EVENT_DATE', 'GOAL_PRIORITY', 'AGE', 'HEIGHT', 'WEIGHT', 'TRAINING_DAYS', 'WEEKDAY_DURATION', 'WEEKEND_DURATION', 'EQUIPMENT', 'POOL_ACCESS', 'BIKE_ACCESS', 'HEALTH_AREAS', 'HEALTH_TIMING', 'HEALTH_DESCRIPTION', 'COACH_TONE', 'COACH_DETAIL', 'BASELINE_SOURCE', 'SUMMARY', name='llm_onboarding_step', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('provider_mode', sa.Enum('mock', 'live', name='llm_provider_mode', native_enum=False, create_constraint=True, length=8), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('SUCCEEDED', 'CLARIFICATION', 'FALLBACK', 'PROVIDER_ERROR', 'RATE_LIMITED', name='llm_usage_status', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('completion_tokens IS NULL OR completion_tokens >= 0', name=op.f('ck_llm_usage_completion_tokens_nonnegative')),
    sa.CheckConstraint('prompt_tokens IS NULL OR prompt_tokens >= 0', name=op.f('ck_llm_usage_prompt_tokens_nonnegative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_llm_usage_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage'))
    )
    op.create_index('ix_llm_usage_user_created', 'llm_usage', ['user_id', 'created_at'], unique=False)
    op.create_table('oauth_states',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('STRAVA_CONNECT', 'STRAVA', name='oauth_provider', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_states_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_states')),
    sa.UniqueConstraint('state_hash', name='uq_oauth_states_state_hash')
    )
    op.create_index('ix_oauth_states_user_expires', 'oauth_states', ['user_id', 'expires_at'], unique=False)
    op.create_table('onboarding_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='onboarding_status', native_enum=False, create_constraint=True, length=16), server_default='ACTIVE', nullable=False),
    sa.Column('current_step', sa.Enum('CONSENT', 'PRIMARY_SPORT', 'GOAL_TYPE', 'EVENT_STATUS', 'EVENT_NAME', 'EVENT_DATE', 'GOAL_PRIORITY', 'AGE', 'HEIGHT', 'WEIGHT', 'TRAINING_DAYS', 'WEEKDAY_DURATION', 'WEEKEND_DURATION', 'EQUIPMENT', 'POOL_ACCESS', 'BIKE_ACCESS', 'HEALTH_AREAS', 'HEALTH_TIMING', 'HEALTH_DESCRIPTION', 'COACH_TONE', 'COACH_DETAIL', 'BASELINE_SOURCE', 'SUMMARY', name='onboarding_step', native_enum=False, create_constraint=True, length=32), server_default='CONSENT', nullable=False),
    sa.Column('answers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('pending_free_text_step', sa.Enum('CONSENT', 'PRIMARY_SPORT', 'GOAL_TYPE', 'EVENT_STATUS', 'EVENT_NAME', 'EVENT_DATE', 'GOAL_PRIORITY', 'AGE', 'HEIGHT', 'WEIGHT', 'TRAINING_DAYS', 'WEEKDAY_DURATION', 'WEEKEND_DURATION', 'EQUIPMENT', 'POOL_ACCESS', 'BIKE_ACCESS', 'HEALTH_AREAS', 'HEALTH_TIMING', 'HEALTH_DESCRIPTION', 'COACH_TONE', 'COACH_DETAIL', 'BASELINE_SOURCE', 'SUMMARY', name='pending_onboarding_step', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('pending_parsed_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('return_to_summary', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_onboarding_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarding_sessions')),
    sa.UniqueConstraint('user_id', name='uq_onboarding_sessions_user_id')
    )
    op.create_table('strava_connections',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('strava_athlete_id', sa.BigInteger(), nullable=False),
    sa.Column('accepted_scopes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=True),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('connection_status', sa.Enum('CONNECTED', 'REFRESH_FAILED', 'DISCONNECTED', 'INSUFFICIENT_SCOPE', name='connection_status', native_enum=False, create_constraint=True, length=24), server_default='CONNECTED', nullable=False),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_strava_connections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strava_connections')),
    sa.UniqueConstraint('strava_athlete_id', name='uq_strava_connections_athlete_id'),
    sa.UniqueConstraint('user_id', name='uq_strava_connections_user_id')
    )
    op.create_table('strava_sync_jobs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', 'RATE_LIMITED', name='sync_status', native_enum=False, create_constraint=True, length=16), server_default='REQUESTED', nullable=False),
    sa.Column('sync_type', sa.Enum('INITIAL', 'MANUAL', 'WEBHOOK', name='sync_type', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('imported_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message_safe', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('failed_count >= 0', name=op.f('ck_strava_sync_jobs_failed_nonnegative')),
    sa.CheckConstraint('imported_count >= 0', name=op.f('ck_strava_sync_jobs_imported_nonnegative')),
    sa.CheckConstraint('skipped_count >= 0', name=op.f('ck_strava_sync_jobs_skipped_nonnegative')),
    sa.CheckConstraint('updated_count >= 0', name=op.f('ck_strava_sync_jobs_updated_nonnegative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_strava_sync_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strava_sync_jobs'))
    )
    op.create_index('ix_strava_sync_jobs_user_requested', 'strava_sync_jobs', ['user_id', 'requested_at'], unique=False)
    op.create_index('uq_strava_sync_jobs_active_user', 'strava_sync_jobs', ['user_id'], unique=True, postgresql_where=sa.text("status IN ('REQUESTED', 'RUNNING')"), sqlite_where=sa.text("status IN ('REQUESTED', 'RUNNING')"))
    op.create_table('strava_webhook_events',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('external_event_key', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('object_type', sa.Enum('activity', 'athlete', name='webhook_object_type', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('object_id', sa.BigInteger(), nullable=False),
    sa.Column('aspect_type', sa.Enum('create', 'update', 'delete', name='webhook_aspect_type', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'PROCESSED', 'IGNORED', 'FAILED', name='webhook_processing_status', native_enum=False, create_constraint=True, length=16), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_strava_webhook_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strava_webhook_events')),
    sa.UniqueConstraint('external_event_key', name='uq_strava_webhook_events_external_key')
    )
    op.create_index('ix_strava_webhook_events_owner_created', 'strava_webhook_events', ['owner_id', 'created_at'], unique=False)
    op.create_index('ix_strava_webhook_events_user_created', 'strava_webhook_events', ['user_id', 'created_at'], unique=False)
    op.create_table('training_goals',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('goal_type', sa.Enum('FIVE_K', 'TEN_K', 'HALF_MARATHON', 'MARATHON', 'TRAIL', 'CYCLING_EVENT', 'GRAN_FONDO', 'SPRINT_TRIATHLON', 'OLYMPIC_TRIATHLON', 'HALF_IRONMAN_70_3', 'IRONMAN', 'FIRST_TRIATHLON', 'IMPROVE_TECHNIQUE', 'OPEN_WATER_SWIMMING', 'SPECIFIC_EVENT', 'GENERAL_HEALTH', 'IMPROVE_ENDURANCE', 'IMPROVE_PERFORMANCE', 'LOSE_BODY_FAT', 'BUILD_STRENGTH', 'OTHER', name='goal_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('goal_priority', sa.Enum('FINISH_SAFELY', 'PERSONAL_BEST', 'TARGET_TIME', 'HEALTH_CONSISTENCY', 'OTHER', name='goal_priority', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_training_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_goals')),
    sa.UniqueConstraint('user_id', name='uq_training_goals_user_id')
    )
    op.create_table('discipline_baselines',
    sa.Column('athlete_baseline_id', sa.Uuid(), nullable=False),
    sa.Column('discipline', sa.Enum('RUN', 'RIDE', 'SWIM', 'STRENGTH', 'WALK_HIKE', 'OTHER', name='baseline_discipline', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('level_label', sa.Enum('UNKNOWN', 'BEGINNER', 'DEVELOPING', 'INTERMEDIATE', 'ADVANCED', name='level_label', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('sessions_count', sa.Integer(), nullable=False),
    sa.Column('active_weeks', sa.Integer(), nullable=False),
    sa.Column('total_duration_seconds', sa.BigInteger(), nullable=False),
    sa.Column('average_weekly_duration_seconds', sa.Float(), nullable=False),
    sa.Column('total_distance_meters', sa.Float(), nullable=True),
    sa.Column('average_weekly_distance_meters', sa.Float(), nullable=True),
    sa.Column('longest_session_seconds', sa.Integer(), nullable=True),
    sa.Column('longest_distance_meters', sa.Float(), nullable=True),
    sa.Column('recent_session_count', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('active_weeks >= 0', name=op.f('ck_discipline_baselines_active_weeks_nonnegative')),
    sa.CheckConstraint('average_weekly_duration_seconds >= 0', name=op.f('ck_discipline_baselines_weekly_duration_nonnegative')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_discipline_baselines_confidence_range')),
    sa.CheckConstraint('recent_session_count >= 0', name=op.f('ck_discipline_baselines_recent_sessions_nonnegative')),
    sa.CheckConstraint('sessions_count >= 0', name=op.f('ck_discipline_baselines_sessions_nonnegative')),
    sa.CheckConstraint('total_duration_seconds >= 0', name=op.f('ck_discipline_baselines_total_duration_nonnegative')),
    sa.ForeignKeyConstraint(['athlete_baseline_id'], ['athlete_baselines.id'], name=op.f('fk_discipline_baselines_athlete_baseline_id_athlete_baselines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discipline_baselines')),
    sa.UniqueConstraint('athlete_baseline_id', 'discipline', name='uq_discipline_baselines_baseline_discipline')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discipline_baselines')
    op.drop_table('training_goals')
    op.drop_index('ix_strava_webhook_events_user_created', table_name='strava_webhook_events')
    op.drop_index('ix_strava_webhook_events_owner_created', table_name='strava_webhook_events')
    op.drop_table('strava_webhook_events')
    op.drop_index('uq_strava_sync_jobs_active_user', table_name='strava_sync_jobs', postgresql_where=sa.text("status IN ('REQUESTED', 'RUNNING')"), sqlite_where=sa.text("status IN ('REQUESTED', 'RUNNING')"))
    op.drop_index('ix_strava_sync_jobs_user_requested', table_name='strava_sync_jobs')
    op.drop_table('strava_sync_jobs')
    op.drop_table('strava_connections')
    op.drop_table('onboarding_sessions')
    op.drop_index('ix_oauth_states_user_expires', table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_index('ix_llm_usage_user_created', table_name='llm_usage')
    op.drop_table('llm_usage')
    op.drop_index('ix_health_constraints_user_id', table_name='health_constraints')
    op.drop_table('health_constraints')
    op.drop_table('equipment_access')
    op.drop_table('coach_preferences')
    op.drop_table('baseline_preferences')
    op.drop_table('availability_rules')
    op.drop_table('athlete_profiles')
    op.drop_index('ix_athlete_baselines_user_generated', table_name='athlete_baselines')
    op.drop_table('athlete_baselines')
    op.drop_index('ix_activities_user_started_at', table_name='activities')
    op.drop_table('activities')
    op.drop_index('ix_users_telegram_user_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
