"""Add deterministic equipment knowledge and goal-scoped statuses.

Revision ID: 0014_deterministic_equipment_knowledge
Revises: 0013_add_athlete_profile_context
"""
from __future__ import annotations

import uuid
from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op

revision = "0014_equipment_knowledge"
down_revision = "0013_add_athlete_profile_context"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("training_goals", sa.Column("equipment_context_revision", sa.Integer(), server_default="1", nullable=False))
    op.create_table("equipment_resources", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("code", sa.String(64), nullable=False), sa.Column("display_name", sa.String(120), nullable=False), sa.Column("category", sa.String(24), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("code"))
    op.create_table("equipment_goal_types", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("code", sa.String(64), nullable=False), sa.Column("match_terms", sa.JSON(), nullable=False), sa.Column("match_priority", sa.SmallInteger(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("code"))
    op.create_table("equipment_stage_windows", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("goal_type_id", sa.Uuid(), sa.ForeignKey("equipment_goal_types.id", ondelete="CASCADE"), nullable=False), sa.Column("stage", sa.String(24), nullable=False), sa.Column("minimum_days_until_event", sa.Integer(), nullable=False), sa.Column("maximum_days_until_event", sa.Integer()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("goal_type_id", "stage"))
    op.create_table("equipment_resource_requirements", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("goal_type_id", sa.Uuid(), sa.ForeignKey("equipment_goal_types.id", ondelete="CASCADE"), nullable=False), sa.Column("resource_id", sa.Uuid(), sa.ForeignKey("equipment_resources.id", ondelete="RESTRICT"), nullable=False), sa.Column("priority", sa.String(16), nullable=False), sa.Column("required_stage", sa.String(24), nullable=False), sa.Column("condition_text", sa.String(300)), sa.Column("display_order", sa.SmallInteger(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("goal_type_id", "resource_id"))
    op.create_table("equipment_resource_substitutions", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("required_resource_id", sa.Uuid(), sa.ForeignKey("equipment_resources.id", ondelete="CASCADE"), nullable=False), sa.Column("substitute_resource_id", sa.Uuid(), sa.ForeignKey("equipment_resources.id", ondelete="CASCADE"), nullable=False), sa.Column("quality", sa.String(24), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("required_resource_id", "substitute_resource_id"))
    op.create_table("athlete_goal_equipment_statuses", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("training_goal_id", sa.Uuid(), sa.ForeignKey("training_goals.id", ondelete="CASCADE"), nullable=False), sa.Column("goal_revision", sa.Integer(), nullable=False), sa.Column("resource_id", sa.Uuid(), sa.ForeignKey("equipment_resources.id", ondelete="RESTRICT"), nullable=False), sa.Column("status", sa.String(16), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("user_id", "training_goal_id", "goal_revision", "resource_id"))
    op.create_table("athlete_goal_equipment_interpretations", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("training_goal_id", sa.Uuid(), sa.ForeignKey("training_goals.id", ondelete="CASCADE"), nullable=False), sa.Column("goal_revision", sa.Integer(), nullable=False), sa.Column("interpretation", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("user_id", "training_goal_id", "goal_revision"))
    bind = op.get_bind(); now = datetime.now(UTC)
    resources = {code: str(uuid.uuid4()) for code in ("running_shoes", "safe_running_route", "trail_shoes", "road_or_tri_bike", "mountain_bike", "indoor_bike", "helmet", "pool_access", "open_water_access", "wetsuit")}
    bind.execute(sa.table("equipment_resources", sa.column("id"), sa.column("code"), sa.column("display_name"), sa.column("category"), sa.column("created_at"), sa.column("updated_at")).insert(), [{"id": resources[c], "code": c, "display_name": name, "category": category, "created_at": now, "updated_at": now} for c, name, category in [("running_shoes", "Running shoes", "EQUIPMENT"), ("safe_running_route", "Safe running route", "TRAINING_RESOURCE"), ("trail_shoes", "Trail running shoes", "EQUIPMENT"), ("road_or_tri_bike", "Road or triathlon bike", "EQUIPMENT"), ("mountain_bike", "Mountain bike", "EQUIPMENT"), ("indoor_bike", "Indoor bike", "EQUIPMENT"), ("helmet", "Helmet", "EQUIPMENT"), ("pool_access", "Pool access", "FACILITY_ACCESS"), ("open_water_access", "Open-water access", "FACILITY_ACCESS"), ("wetsuit", "Wetsuit", "EQUIPMENT")]])
    types = {code: str(uuid.uuid4()) for code in ("run_5k", "run_10k", "half_marathon", "marathon", "road_cycling", "pool_swimming", "open_water_swimming", "tri_sprint", "tri_olympic", "tri_703", "tri_ironman", "trail_running")}
    terms = {"run_5k":["5k", "5 km"], "run_10k":["10k", "10 km"], "half_marathon":["half marathon"], "marathon":["marathon"], "road_cycling":["road cycling", "gran fondo"], "pool_swimming":["pool swimming"], "open_water_swimming":["open water"], "tri_sprint":["sprint triathlon"], "tri_olympic":["olympic triathlon"], "tri_703":["70.3", "half ironman"], "tri_ironman":["ironman"], "trail_running":["trail"]}
    gt = sa.table("equipment_goal_types", sa.column("id"), sa.column("code"), sa.column("match_terms", sa.JSON()), sa.column("match_priority"), sa.column("created_at"), sa.column("updated_at")); bind.execute(gt.insert(), [{"id": types[c], "code": c, "match_terms": terms[c], "match_priority": i, "created_at": now, "updated_at": now} for i,c in enumerate(types)])
    win = sa.table("equipment_stage_windows", sa.column("id"), sa.column("goal_type_id"), sa.column("stage"), sa.column("minimum_days_until_event"), sa.column("maximum_days_until_event"), sa.column("created_at"), sa.column("updated_at")); bind.execute(win.insert(), [{"id":str(uuid.uuid4()),"goal_type_id":tid,"stage":stage,"minimum_days_until_event":low,"maximum_days_until_event":high,"created_at":now,"updated_at":now} for tid in types.values() for stage,low,high in [("RACE",0,7),("RACE_SPECIFIC",8,56),("BUILD",57,180),("BASE",181,None)]])
    req = sa.table("equipment_resource_requirements", sa.column("id"), sa.column("goal_type_id"), sa.column("resource_id"), sa.column("priority"), sa.column("required_stage"), sa.column("condition_text"), sa.column("display_order"), sa.column("created_at"), sa.column("updated_at"))
    tri = [("running_shoes","Essential","START",None),("pool_access","Essential","START",None),("road_or_tri_bike","Essential","RACE_SPECIFIC",None),("helmet","Essential","BASE","For outdoor cycling"),("wetsuit","Optional","RACE_SPECIFIC","If race rules and water conditions require it")]
    run = [("running_shoes","Essential","START",None),("safe_running_route","Recommended","START",None)]
    data = [(code, tri if code.startswith("tri_") else [("road_or_tri_bike","Essential","BASE",None),("helmet","Essential","BASE","For outdoor cycling")] if code=="road_cycling" else [("pool_access","Essential","START",None)] if code=="pool_swimming" else [("open_water_access","Essential","BASE",None),("wetsuit","Optional","RACE_SPECIFIC","If conditions require it")] if code=="open_water_swimming" else [("trail_shoes","Essential","START",None),("safe_running_route","Recommended","START",None)] if code=="trail_running" else run) for code in types]
    bind.execute(req.insert(), [{"id":str(uuid.uuid4()),"goal_type_id":types[code],"resource_id":resources[resource],"priority":priority,"required_stage":stage,"condition_text":condition,"display_order":order,"created_at":now,"updated_at":now} for code, items in data for order,(resource,priority,stage,condition) in enumerate(items,1)])
    sub = sa.table("equipment_resource_substitutions", sa.column("id"), sa.column("required_resource_id"), sa.column("substitute_resource_id"), sa.column("quality"), sa.column("created_at"), sa.column("updated_at")); bind.execute(sub.insert(), [{"id":str(uuid.uuid4()),"required_resource_id":resources["road_or_tri_bike"],"substitute_resource_id":resources["mountain_bike"],"quality":"PARTIAL","created_at":now,"updated_at":now},{"id":str(uuid.uuid4()),"required_resource_id":resources["road_or_tri_bike"],"substitute_resource_id":resources["indoor_bike"],"quality":"FITNESS_ONLY","created_at":now,"updated_at":now}])


def downgrade() -> None:
    for table in ("athlete_goal_equipment_interpretations", "athlete_goal_equipment_statuses", "equipment_resource_substitutions", "equipment_resource_requirements", "equipment_stage_windows", "equipment_goal_types", "equipment_resources"): op.drop_table(table)
    op.drop_column("training_goals", "equipment_context_revision")
