"""Explicit persisted and application enums."""

from __future__ import annotations

from enum import StrEnum


class UserStatus(StrEnum):
    NEW = "NEW"
    ONBOARDING_IN_PROGRESS = "ONBOARDING_IN_PROGRESS"
    ONBOARDING_COMPLETED = "ONBOARDING_COMPLETED"
    PROFILE_COMPLETED = "PROFILE_COMPLETED"
    BASELINE_PENDING = "BASELINE_PENDING"
    BASELINE_IMPORTING = "BASELINE_IMPORTING"
    BASELINE_READY = "BASELINE_READY"
    BASELINE_FAILED = "BASELINE_FAILED"


class OnboardingStatus(StrEnum):
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class OnboardingStep(StrEnum):
    CONSENT = "CONSENT"
    SETUP_INTRODUCTION = "SETUP_INTRODUCTION"
    GOAL_INTAKE = "GOAL_INTAKE"
    GOAL_CONFIRMED = "GOAL_CONFIRMED"
    PROFILE_BIRTH_YEAR_INTAKE = "PROFILE_BIRTH_YEAR_INTAKE"
    PROFILE_GENDER_INTAKE = "PROFILE_GENDER_INTAKE"
    PROFILE_WEIGHT_INTAKE = "PROFILE_WEIGHT_INTAKE"
    PROFILE_HEIGHT_INTAKE = "PROFILE_HEIGHT_INTAKE"
    AVAILABILITY_INTAKE = "AVAILABILITY_INTAKE"
    EQUIPMENT_RECOMMENDATION = "EQUIPMENT_RECOMMENDATION"
    EQUIPMENT_INTAKE = "EQUIPMENT_INTAKE"
    EQUIPMENT_DETAILS_INTAKE = "EQUIPMENT_DETAILS_INTAKE"
    HEALTH_LIMITATIONS_INTAKE = "HEALTH_LIMITATIONS_INTAKE"


class AthleteGender(StrEnum):
    """Competition category / biological-sex value supplied by the athlete."""

    MALE = "MALE"
    FEMALE = "FEMALE"
    OTHER_UNSPECIFIED = "OTHER_UNSPECIFIED"


class PrimarySport(StrEnum):
    RUNNING = "RUNNING"
    CYCLING = "CYCLING"
    TRIATHLON = "TRIATHLON"
    SWIMMING = "SWIMMING"
    GENERAL_FITNESS = "GENERAL_FITNESS"
    OTHER = "OTHER"


class BaselineSource(StrEnum):
    STRAVA = "STRAVA"
    APPLE_HEALTH_EXPORT = "APPLE_HEALTH_EXPORT"
    FILE_IMPORT = "FILE_IMPORT"
    MANUAL = "MANUAL"
    CALIBRATION = "CALIBRATION"
    SKIP_FOR_NOW = "SKIP_FOR_NOW"


class BaselinePreferenceStatus(StrEnum):
    SELECTED = "SELECTED"
    PENDING = "PENDING"
    IMPORTING = "IMPORTING"
    READY = "READY"
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
    FAILED = "FAILED"


class OAuthProvider(StrEnum):
    STRAVA_CONNECT = "STRAVA_CONNECT"
    STRAVA = "STRAVA"


class ConnectionStatus(StrEnum):
    CONNECTED = "CONNECTED"
    REFRESH_FAILED = "REFRESH_FAILED"
    DISCONNECTED = "DISCONNECTED"
    INSUFFICIENT_SCOPE = "INSUFFICIENT_SCOPE"


class ActivitySource(StrEnum):
    MANUAL = "MANUAL"
    STRAVA = "STRAVA"
    APPLE_HEALTH = "APPLE_HEALTH"
    TCX = "TCX"
    FIT = "FIT"
    OTHER_IMPORT = "OTHER_IMPORT"


class HeartRateTemporalQuality(StrEnum):
    EXACT_SAMPLE = "EXACT_SAMPLE"
    SHORT_INTERVAL = "SHORT_INTERVAL"
    COARSE_INTERVAL = "COARSE_INTERVAL"
    UNKNOWN = "UNKNOWN"


class TrainingFileFormat(StrEnum):
    APPLE_HEALTH_ZIP = "APPLE_HEALTH_ZIP"
    TCX = "TCX"
    UNKNOWN = "UNKNOWN"


class WorkoutFlowStep(StrEnum):
    WAITING_FOR_FILE = "WAITING_FOR_FILE"
    HR_OFFER = "HR_OFFER"
    HR_ENTRY = "HR_ENTRY"
    HR_CONFIRM = "HR_CONFIRM"
    RPE = "RPE"
    MOBILITY = "MOBILITY"
    DISCOMFORT = "DISCOMFORT"
    BODY_AREA = "BODY_AREA"
    DESCRIPTION_ENTRY = "DESCRIPTION_ENTRY"
    DESCRIPTION_CONFIRM = "DESCRIPTION_CONFIRM"
    SEVERITY = "SEVERITY"
    COMPLETE = "COMPLETE"
    CANCELLED = "CANCELLED"


class DiscomfortSeverity(StrEnum):
    MILD = "MILD"
    MODERATE = "MODERATE"
    SEVERE = "SEVERE"


class AppleHealthImportStatus(StrEnum):
    RECEIVED = "RECEIVED"
    PROCESSING = "PROCESSING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class Discipline(StrEnum):
    RUNNING = "RUNNING"
    CYCLING = "CYCLING"
    HIKING = "HIKING"
    SWIMMING = "SWIMMING"
    STRENGTH = "STRENGTH"
    OTHER = "OTHER"

    # Source-compatible aliases. Only the canonical values above are persisted
    # or yielded when iterating over the enum.
    RUN = "RUNNING"
    RIDE = "CYCLING"
    WALK_HIKE = "HIKING"
    SWIM = "SWIMMING"


class RunningType(StrEnum):
    OUTDOOR = "OUTDOOR"
    TRAIL = "TRAIL"
    TRACK = "TRACK"
    TREADMILL = "TREADMILL"


class CyclingType(StrEnum):
    ROAD = "ROAD"
    MTB = "MTB"
    GRAVEL = "GRAVEL"
    STATIONARY = "STATIONARY"
    OTHER = "OTHER"


class HikingType(StrEnum):
    HIKING = "HIKING"
    TREKKING = "TREKKING"
    MOUNTAINEERING = "MOUNTAINEERING"
    SNOWSHOEING = "SNOWSHOEING"
    OTHER = "OTHER"


class SwimmingEnvironment(StrEnum):
    POOL = "POOL"
    OPEN_WATER = "OPEN_WATER"


class SwimmingStroke(StrEnum):
    FREESTYLE = "FREESTYLE"
    BREASTSTROKE = "BREASTSTROKE"
    BACKSTROKE = "BACKSTROKE"
    BUTTERFLY = "BUTTERFLY"
    MIXED = "MIXED"
    OTHER = "OTHER"


class StrengthType(StrEnum):
    GYM = "GYM"
    CALISTHENICS = "CALISTHENICS"
    OTHER = "OTHER"


class SyncStatus(StrEnum):
    REQUESTED = "REQUESTED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    RATE_LIMITED = "RATE_LIMITED"


class SyncType(StrEnum):
    INITIAL = "INITIAL"
    MANUAL = "MANUAL"
    WEBHOOK = "WEBHOOK"


class WebhookProcessingStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    IGNORED = "IGNORED"
    FAILED = "FAILED"


class BaselineStatus(StrEnum):
    READY = "READY"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    FAILED = "FAILED"


class LevelLabel(StrEnum):
    UNKNOWN = "UNKNOWN"
    BEGINNER = "BEGINNER"
    DEVELOPING = "DEVELOPING"
    INTERMEDIATE = "INTERMEDIATE"
    ADVANCED = "ADVANCED"


class LLMUsageStatus(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    CLARIFICATION = "CLARIFICATION"
    FALLBACK = "FALLBACK"
    PROVIDER_ERROR = "PROVIDER_ERROR"
    RATE_LIMITED = "RATE_LIMITED"


class TrainingGoalStatus(StrEnum):
    """Lifecycle state for an explicitly confirmed canonical goal."""

    CONFIRMED = "CONFIRMED"


class CoachTone(StrEnum):
    DIRECT_DEMANDING = "DIRECT_DEMANDING"
    ANALYTICAL_DETAILED = "ANALYTICAL_DETAILED"
    CONCISE_PRACTICAL = "CONCISE_PRACTICAL"
    SUPPORTIVE_MOTIVATIONAL = "SUPPORTIVE_MOTIVATIONAL"


class DetailLevel(StrEnum):
    SHORT = "SHORT"
    MEDIUM = "MEDIUM"
    DETAILED = "DETAILED"


class DayOfWeek(StrEnum):
    MONDAY = "MONDAY"
    TUESDAY = "TUESDAY"
    WEDNESDAY = "WEDNESDAY"
    THURSDAY = "THURSDAY"
    FRIDAY = "FRIDAY"
    SATURDAY = "SATURDAY"
    SUNDAY = "SUNDAY"


class WebhookObjectType(StrEnum):
    ACTIVITY = "activity"
    ATHLETE = "athlete"


class WebhookAspectType(StrEnum):
    CREATE = "create"
    UPDATE = "update"
    DELETE = "delete"
