"""Explicit persisted and application enums."""

from __future__ import annotations

from enum import StrEnum


class UserStatus(StrEnum):
    NEW = "NEW"
    ONBOARDING_IN_PROGRESS = "ONBOARDING_IN_PROGRESS"
    PROFILE_COMPLETED = "PROFILE_COMPLETED"
    BASELINE_PENDING = "BASELINE_PENDING"
    BASELINE_IMPORTING = "BASELINE_IMPORTING"
    BASELINE_READY = "BASELINE_READY"
    BASELINE_FAILED = "BASELINE_FAILED"


class OnboardingStatus(StrEnum):
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class OnboardingStep(StrEnum):
    CONSENT = "CONSENT"
    PRIMARY_SPORT = "PRIMARY_SPORT"
    GOAL_TYPE = "GOAL_TYPE"
    EVENT_STATUS = "EVENT_STATUS"
    EVENT_NAME = "EVENT_NAME"
    EVENT_DATE = "EVENT_DATE"
    GOAL_PRIORITY = "GOAL_PRIORITY"
    AGE = "AGE"
    HEIGHT = "HEIGHT"
    WEIGHT = "WEIGHT"
    TRAINING_DAYS = "TRAINING_DAYS"
    WEEKDAY_DURATION = "WEEKDAY_DURATION"
    WEEKEND_DURATION = "WEEKEND_DURATION"
    EQUIPMENT = "EQUIPMENT"
    POOL_ACCESS = "POOL_ACCESS"
    BIKE_ACCESS = "BIKE_ACCESS"
    HEALTH_AREAS = "HEALTH_AREAS"
    HEALTH_TIMING = "HEALTH_TIMING"
    HEALTH_DESCRIPTION = "HEALTH_DESCRIPTION"
    COACH_TONE = "COACH_TONE"
    COACH_DETAIL = "COACH_DETAIL"
    BASELINE_SOURCE = "BASELINE_SOURCE"
    SUMMARY = "SUMMARY"


class PrimarySport(StrEnum):
    RUNNING = "RUNNING"
    CYCLING = "CYCLING"
    TRIATHLON = "TRIATHLON"
    SWIMMING = "SWIMMING"
    GENERAL_FITNESS = "GENERAL_FITNESS"
    OTHER = "OTHER"


class BaselineSource(StrEnum):
    STRAVA = "STRAVA"
    MANUAL = "MANUAL"
    CALIBRATION = "CALIBRATION"
    SKIP_FOR_NOW = "SKIP_FOR_NOW"


class BaselinePreferenceStatus(StrEnum):
    SELECTED = "SELECTED"
    PENDING = "PENDING"
    IMPORTING = "IMPORTING"
    READY = "READY"
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
    FAILED = "FAILED"


class OAuthProvider(StrEnum):
    STRAVA_CONNECT = "STRAVA_CONNECT"
    STRAVA = "STRAVA"


class ConnectionStatus(StrEnum):
    CONNECTED = "CONNECTED"
    REFRESH_FAILED = "REFRESH_FAILED"
    DISCONNECTED = "DISCONNECTED"
    INSUFFICIENT_SCOPE = "INSUFFICIENT_SCOPE"


class ActivitySource(StrEnum):
    STRAVA = "STRAVA"


class Discipline(StrEnum):
    RUN = "RUN"
    RIDE = "RIDE"
    SWIM = "SWIM"
    STRENGTH = "STRENGTH"
    WALK_HIKE = "WALK_HIKE"
    OTHER = "OTHER"


class SyncStatus(StrEnum):
    REQUESTED = "REQUESTED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    RATE_LIMITED = "RATE_LIMITED"


class SyncType(StrEnum):
    INITIAL = "INITIAL"
    MANUAL = "MANUAL"
    WEBHOOK = "WEBHOOK"


class WebhookProcessingStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    IGNORED = "IGNORED"
    FAILED = "FAILED"


class BaselineStatus(StrEnum):
    READY = "READY"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    FAILED = "FAILED"


class LevelLabel(StrEnum):
    UNKNOWN = "UNKNOWN"
    BEGINNER = "BEGINNER"
    DEVELOPING = "DEVELOPING"
    INTERMEDIATE = "INTERMEDIATE"
    ADVANCED = "ADVANCED"


class LLMUsageStatus(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    CLARIFICATION = "CLARIFICATION"
    FALLBACK = "FALLBACK"
    PROVIDER_ERROR = "PROVIDER_ERROR"
    RATE_LIMITED = "RATE_LIMITED"


class GoalPriority(StrEnum):
    FINISH_SAFELY = "FINISH_SAFELY"
    PERSONAL_BEST = "PERSONAL_BEST"
    TARGET_TIME = "TARGET_TIME"
    HEALTH_CONSISTENCY = "HEALTH_CONSISTENCY"
    OTHER = "OTHER"


class CoachTone(StrEnum):
    DIRECT_DEMANDING = "DIRECT_DEMANDING"
    ANALYTICAL_DETAILED = "ANALYTICAL_DETAILED"
    CONCISE_PRACTICAL = "CONCISE_PRACTICAL"
    SUPPORTIVE_MOTIVATIONAL = "SUPPORTIVE_MOTIVATIONAL"


class DetailLevel(StrEnum):
    SHORT = "SHORT"
    MEDIUM = "MEDIUM"
    DETAILED = "DETAILED"


class DayOfWeek(StrEnum):
    MONDAY = "MONDAY"
    TUESDAY = "TUESDAY"
    WEDNESDAY = "WEDNESDAY"
    THURSDAY = "THURSDAY"
    FRIDAY = "FRIDAY"
    SATURDAY = "SATURDAY"
    SUNDAY = "SUNDAY"


class WebhookObjectType(StrEnum):
    ACTIVITY = "activity"
    ATHLETE = "athlete"


class WebhookAspectType(StrEnum):
    CREATE = "create"
    UPDATE = "update"
    DELETE = "delete"
