"""Explicit persisted and application enums."""

from __future__ import annotations

from enum import StrEnum


class UserStatus(StrEnum):
    NEW = "NEW"
    ONBOARDING_IN_PROGRESS = "ONBOARDING_IN_PROGRESS"
    PROFILE_COMPLETED = "PROFILE_COMPLETED"
    BASELINE_PENDING = "BASELINE_PENDING"
    BASELINE_IMPORTING = "BASELINE_IMPORTING"
    BASELINE_READY = "BASELINE_READY"
    BASELINE_FAILED = "BASELINE_FAILED"


class OnboardingStatus(StrEnum):
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class OnboardingStep(StrEnum):
    CONSENT = "CONSENT"
    PRIMARY_SPORT = "PRIMARY_SPORT"
    GOAL_TYPE = "GOAL_TYPE"
    EVENT_STATUS = "EVENT_STATUS"
    EVENT_NAME = "EVENT_NAME"
    EVENT_DATE = "EVENT_DATE"
    GOAL_PRIORITY = "GOAL_PRIORITY"
    AGE = "AGE"
    HEIGHT = "HEIGHT"
    WEIGHT = "WEIGHT"
    TRAINING_DAYS = "TRAINING_DAYS"
    WEEKDAY_DURATION = "WEEKDAY_DURATION"
    WEEKEND_DURATION = "WEEKEND_DURATION"
    EQUIPMENT = "EQUIPMENT"
    POOL_ACCESS = "POOL_ACCESS"
    BIKE_ACCESS = "BIKE_ACCESS"
    HEALTH_AREAS = "HEALTH_AREAS"
    HEALTH_TIMING = "HEALTH_TIMING"
    HEALTH_DESCRIPTION = "HEALTH_DESCRIPTION"
    COACH_TONE = "COACH_TONE"
    COACH_DETAIL = "COACH_DETAIL"
    BASELINE_SOURCE = "BASELINE_SOURCE"
    APPLE_HEALTH_PRIVACY_NOTICE = "APPLE_HEALTH_PRIVACY_NOTICE"
    APPLE_HEALTH_WAITING_FOR_FILE = "APPLE_HEALTH_WAITING_FOR_FILE"
    APPLE_HEALTH_PROCESSING = "APPLE_HEALTH_PROCESSING"
    APPLE_HEALTH_IMPORT_COMPLETE = "APPLE_HEALTH_IMPORT_COMPLETE"
    APPLE_HEALTH_IMPORT_FAILED = "APPLE_HEALTH_IMPORT_FAILED"
    FILE_IMPORT_WAITING = "FILE_IMPORT_WAITING"
    FILE_IMPORT_PROCESSING = "FILE_IMPORT_PROCESSING"
    FILE_IMPORT_COMPLETE = "FILE_IMPORT_COMPLETE"
    SUMMARY = "SUMMARY"


class PrimarySport(StrEnum):
    RUNNING = "RUNNING"
    CYCLING = "CYCLING"
    TRIATHLON = "TRIATHLON"
    SWIMMING = "SWIMMING"
    GENERAL_FITNESS = "GENERAL_FITNESS"
    OTHER = "OTHER"


class BaselineSource(StrEnum):
    STRAVA = "STRAVA"
    APPLE_HEALTH_EXPORT = "APPLE_HEALTH_EXPORT"
    FILE_IMPORT = "FILE_IMPORT"
    MANUAL = "MANUAL"
    CALIBRATION = "CALIBRATION"
    SKIP_FOR_NOW = "SKIP_FOR_NOW"


class BaselinePreferenceStatus(StrEnum):
    SELECTED = "SELECTED"
    PENDING = "PENDING"
    IMPORTING = "IMPORTING"
    READY = "READY"
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
    FAILED = "FAILED"


class OAuthProvider(StrEnum):
    STRAVA_CONNECT = "STRAVA_CONNECT"
    STRAVA = "STRAVA"


class ConnectionStatus(StrEnum):
    CONNECTED = "CONNECTED"
    REFRESH_FAILED = "REFRESH_FAILED"
    DISCONNECTED = "DISCONNECTED"
    INSUFFICIENT_SCOPE = "INSUFFICIENT_SCOPE"


class ActivitySource(StrEnum):
    MANUAL = "MANUAL"
    STRAVA = "STRAVA"
    APPLE_HEALTH = "APPLE_HEALTH"
    TCX = "TCX"
    FIT = "FIT"
    OTHER_IMPORT = "OTHER_IMPORT"


class HeartRateTemporalQuality(StrEnum):
    EXACT_SAMPLE = "EXACT_SAMPLE"
    SHORT_INTERVAL = "SHORT_INTERVAL"
    COARSE_INTERVAL = "COARSE_INTERVAL"
    UNKNOWN = "UNKNOWN"


class TrainingFileFormat(StrEnum):
    APPLE_HEALTH_ZIP = "APPLE_HEALTH_ZIP"
    TCX = "TCX"
    UNKNOWN = "UNKNOWN"


class TrainingImportContext(StrEnum):
    ONBOARDING = "ONBOARDING"
    DAILY = "DAILY"


class WorkoutFlowStep(StrEnum):
    WAITING_FOR_FILE = "WAITING_FOR_FILE"
    HR_OFFER = "HR_OFFER"
    HR_ENTRY = "HR_ENTRY"
    HR_CONFIRM = "HR_CONFIRM"
    RPE = "RPE"
    MOBILITY = "MOBILITY"
    DISCOMFORT = "DISCOMFORT"
    BODY_AREA = "BODY_AREA"
    DESCRIPTION_ENTRY = "DESCRIPTION_ENTRY"
    DESCRIPTION_CONFIRM = "DESCRIPTION_CONFIRM"
    SEVERITY = "SEVERITY"
    COMPLETE = "COMPLETE"
    CANCELLED = "CANCELLED"


class DiscomfortSeverity(StrEnum):
    MILD = "MILD"
    MODERATE = "MODERATE"
    SEVERE = "SEVERE"


class AppleHealthImportStatus(StrEnum):
    RECEIVED = "RECEIVED"
    PROCESSING = "PROCESSING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class Discipline(StrEnum):
    RUNNING = "RUNNING"
    CYCLING = "CYCLING"
    HIKING = "HIKING"
    SWIMMING = "SWIMMING"
    STRENGTH = "STRENGTH"
    OTHER = "OTHER"

    # Source-compatible aliases. Only the canonical values above are persisted
    # or yielded when iterating over the enum.
    RUN = "RUNNING"
    RIDE = "CYCLING"
    WALK_HIKE = "HIKING"
    SWIM = "SWIMMING"


class RunningType(StrEnum):
    OUTDOOR = "OUTDOOR"
    TRAIL = "TRAIL"
    TRACK = "TRACK"
    TREADMILL = "TREADMILL"


class CyclingType(StrEnum):
    ROAD = "ROAD"
    MTB = "MTB"
    GRAVEL = "GRAVEL"
    STATIONARY = "STATIONARY"
    OTHER = "OTHER"


class HikingType(StrEnum):
    HIKING = "HIKING"
    TREKKING = "TREKKING"
    MOUNTAINEERING = "MOUNTAINEERING"
    SNOWSHOEING = "SNOWSHOEING"
    OTHER = "OTHER"


class SwimmingEnvironment(StrEnum):
    POOL = "POOL"
    OPEN_WATER = "OPEN_WATER"


class SwimmingStroke(StrEnum):
    FREESTYLE = "FREESTYLE"
    BREASTSTROKE = "BREASTSTROKE"
    BACKSTROKE = "BACKSTROKE"
    BUTTERFLY = "BUTTERFLY"
    MIXED = "MIXED"
    OTHER = "OTHER"


class StrengthType(StrEnum):
    GYM = "GYM"
    CALISTHENICS = "CALISTHENICS"
    OTHER = "OTHER"


class SyncStatus(StrEnum):
    REQUESTED = "REQUESTED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    RATE_LIMITED = "RATE_LIMITED"


class SyncType(StrEnum):
    INITIAL = "INITIAL"
    MANUAL = "MANUAL"
    WEBHOOK = "WEBHOOK"


class WebhookProcessingStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    IGNORED = "IGNORED"
    FAILED = "FAILED"


class BaselineStatus(StrEnum):
    READY = "READY"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    FAILED = "FAILED"


class LevelLabel(StrEnum):
    UNKNOWN = "UNKNOWN"
    BEGINNER = "BEGINNER"
    DEVELOPING = "DEVELOPING"
    INTERMEDIATE = "INTERMEDIATE"
    ADVANCED = "ADVANCED"


class LLMUsageStatus(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    CLARIFICATION = "CLARIFICATION"
    FALLBACK = "FALLBACK"
    PROVIDER_ERROR = "PROVIDER_ERROR"
    RATE_LIMITED = "RATE_LIMITED"


class GoalPriority(StrEnum):
    FINISH_SAFELY = "FINISH_SAFELY"
    PERSONAL_BEST = "PERSONAL_BEST"
    TARGET_TIME = "TARGET_TIME"
    HEALTH_CONSISTENCY = "HEALTH_CONSISTENCY"
    OTHER = "OTHER"


class CoachTone(StrEnum):
    DIRECT_DEMANDING = "DIRECT_DEMANDING"
    ANALYTICAL_DETAILED = "ANALYTICAL_DETAILED"
    CONCISE_PRACTICAL = "CONCISE_PRACTICAL"
    SUPPORTIVE_MOTIVATIONAL = "SUPPORTIVE_MOTIVATIONAL"


class DetailLevel(StrEnum):
    SHORT = "SHORT"
    MEDIUM = "MEDIUM"
    DETAILED = "DETAILED"


class DayOfWeek(StrEnum):
    MONDAY = "MONDAY"
    TUESDAY = "TUESDAY"
    WEDNESDAY = "WEDNESDAY"
    THURSDAY = "THURSDAY"
    FRIDAY = "FRIDAY"
    SATURDAY = "SATURDAY"
    SUNDAY = "SUNDAY"


class WebhookObjectType(StrEnum):
    ACTIVITY = "activity"
    ATHLETE = "athlete"


class WebhookAspectType(StrEnum):
    CREATE = "create"
    UPDATE = "update"
    DELETE = "delete"
